// File: src/main/java/domain/game/CardType.java
package model;

public enum CardType {
	NOPE(GameType.EXPLODING_KITTENS),
	DEFUSE(GameType.EXPLODING_KITTENS),
	ATTACK(GameType.EXPLODING_KITTENS),
	SHUFFLE(GameType.EXPLODING_KITTENS),
	SKIP(GameType.EXPLODING_KITTENS),
	SEE_THE_FUTURE(GameType.EXPLODING_KITTENS),
	CAT_ONE(GameType.EXPLODING_KITTENS),
	CAT_TWO(GameType.EXPLODING_KITTENS),
	CAT_THREE(GameType.EXPLODING_KITTENS),
	CAT_FOUR(GameType.EXPLODING_KITTENS),
	EXPLODING_KITTEN(GameType.EXPLODING_KITTENS),
	STREAKING_KITTEN(GameType.STREAKING_KITTENS),
	SWAP_TOP_AND_BOTTOM(GameType.STREAKING_KITTENS),
	GARBAGE_COLLECTION(GameType.STREAKING_KITTENS),
	CURSE_OF_THE_CAT_BUTT(GameType.STREAKING_KITTENS),
	ALTER_THE_FUTURE(GameType.STREAKING_KITTENS),
	CATOMIC_BOMB(GameType.STREAKING_KITTENS),
	SUPER_SKIP(GameType.STREAKING_KITTENS),
	MARK(GameType.STREAKING_KITTENS),
	IMPLODING_KITTEN(GameType.IMPLODING_KITTENS),
	REVERSE(GameType.IMPLODING_KITTENS),
	FERAL_CAT(GameType.IMPLODING_KITTENS),
	TARGETED_ATTACK(GameType.IMPLODING_KITTENS),
	DRAW_FROM_THE_BOTTOM(GameType.IMPLODING_KITTENS);

	private final GameType gameType;

	CardType(GameType gameType) {
		this.gameType = gameType;
	}

	public GameType getGameType() {
		return gameType;
	}
}
