@startuml

package model {

    class Game {
        - numberOfPlayers: int
        - gameType: GameType
        - deck: Deck
        - players: Player[]
        - rand: Random
        - currentPlayerTurn: int
        - currentPlayerNumberOfTurns: int
        - isReversed: boolean
        - attackQueue: List<Integer>
        - attackCounter: int
        - numberOfAttacks: int
        - turnTracker: int[]
        - attacked: boolean
        - discardPile: DiscardPile

        + Game(numberOfPlayers: int,
               gameType: GameType,
               deck: Deck,
               players: Player[],
               rand: Random,
               attackQueue: List<Integer>,
               turnTracker: int[])

        + getNumberOfPlayers(): int
        + getGameType(): GameType
        + getDeck(): Deck
        + getDiscardPile(): DiscardPile
        + getPlayerAtIndex(playerIndex: int): Player
        + getPlayerTurn(): int
        + getNumberOfTurns(): int
        + setNumberOfPlayers(numberOfPlayers: int): void

        + drawCard(): Card
        + drawFromBottom(): Card
        + getDeckSize(): int
        + getCardAtIndex(cardIndex: int): Card

        + playExplodingKitten(playerIndex: int): boolean
        + playDefuse(idxToInsert: int, playerIndex: int): void
        + playShuffle(numberOfShuffles: int): void
        + playSkip(superSkip: boolean): int
        + playReverse(): void
        + playMark(playerIndex: int, cardIndex: int): void

        + checkNumberOfAlivePlayers(): int
        + incrementPlayerTurn(): void
        + decrementNumberOfTurns(): void
        + setCurrentPlayerNumberOfTurns(turns: int): void
        + setTurnToTargetedIndexIfAttackOccurred(): void
        + checkIfPlayerDead(playerIndex: int): boolean
        + checkIfPlayerHasCard(playerIndex: int, cardType: CardType): boolean
    }

    Game --> Deck
    Game --> " *" Player
    Game --> GameType
    Game --> DiscardPile

    class Deck {
        - deck: List<Card>
        - rand: Random
        - gameType: GameType
        - numberOfPlayers: int
        - maxDeckSize: int
        - instantiator: Instantiator

        + Deck(deck: List<Card>, rand: Random,
               gameType: GameType, numberOfPlayers: int,
               maxDeckSize: int, instantiator: Instantiator)

        + getDeckSize(): int
        + getCardAtIndex(index: int): Card
        + shuffleDeck(): void
        + insertCard(cardType: CardType, numberOfCards: int, bottom: boolean): void
        + drawCard(): Card
        + drawCardFromBottom(): Card
        + setNumberOfPlayers(numberOfPlayers: int): void
        + chooseGameType(gameType: GameType): void
        + removeBombs(): int
        + insertExplodingKittenAtIndex(indexToInsert: int): void
        + insertImplodingKittenAtIndex(indexToInsert: int, card: Card): void
        + reorderDeckCards(newOrderIndices: int[], cardsToReorder: List<Card>): void
    }

    Deck --> CardType
    Deck --> GameType
    Deck --> Instantiator
    Deck --> "*" Card

    class Player {
        - playerID: int
        - hand: List<Card>
        - isDead: boolean
        - rand: Random
        - isCursed: boolean

        + Player(playerID: int, instantiator: Instantiator)

        + getPlayerID(): int
        + addCardToHand(card: Card): void
        + hasCard(cardType: CardType): boolean
        + getHandSize(): int
        + getCardAt(index: int): Card
        + getIndexOfCard(cardType: CardType): int
        + removeCardFromHand(index: int): Card
        + shuffleHand(): void
        + checkNumberOfCardsInHand(cardType: CardType): int
        + getIsDead(): boolean
        + setIsDead(): void
        + getIsCursed(): boolean
        + setCursed(isCursed: boolean): void
    }

    Player --> " *" Card
    Player --> CardType
    Player --> Instantiator

    class Card {
        - cardType: CardType
        - isMarked: boolean
        - isFacedUp: boolean

        + Card(cardType: CardType)
        + getCardType(): CardType
        + markCard(): void
        + checkIfMarked(): boolean
        + setFacedUp(): void
        + checkIfFacedUp(): boolean
    }

    Card --> CardType

    class DiscardPile {
        - cards: List<Card>

        + discard(card: Card): void
        + size(): int
        + peekTop(): Card
    }

    DiscardPile --> "*" Card

    interface IGamePrompts {
        + askExplodingKittenInsertIndex(maxIndex: int): int
        + showTopCards(active: Player, cards: List<Card>): void
        + showDeckShuffled(): void
        + askPlayerWantsToPlayNope(reactingPlayer: Player, originalCard: Card): boolean
    }

    interface CardEffect {
        + apply(ctx: CardPlayContext): void
    }

    class CardPlayContext {
        - game: Game
        - activePlayer: Player
        - card: Card
        - prompts: IGamePrompts

        + CardPlayContext(game: Game,
                          activePlayer: Player,
                          card: Card,
                          prompts: IGamePrompts)

        + getGame(): Game
        + getActivePlayer(): Player
        + getCard(): Card
        + getPrompts(): IGamePrompts
        + getDeck(): Deck
        + getDiscardPile(): DiscardPile
    }

    CardPlayContext --> Game
    CardPlayContext --> Player
    CardPlayContext --> Card
    CardPlayContext --> IGamePrompts
    CardPlayContext --> Deck
    CardPlayContext --> DiscardPile

    class CardEffectRegistry {
        - effects: Map<CardType, CardEffect>

        + CardEffectRegistry(game: Game, prompts: IGamePrompts)
        + getEffect(type: CardType): CardEffect
    }

    CardEffectRegistry --> CardEffect
    CardEffectRegistry --> CardType

    class CardPlayService {
        - game: Game
        - prompts: IGamePrompts
        - registry: CardEffectRegistry

        + CardPlayService(game: Game, prompts: IGamePrompts)
        + playCard(activePlayer: Player, handIndex: int): void
        - isCanceledByNope(originalCard: Card,
                           originalPlayer: Player): boolean
    }

    CardPlayService --> Game
    CardPlayService --> IGamePrompts
    CardPlayService --> CardEffectRegistry


    class ExplodingKittenEffect {
        + apply(ctx: CardPlayContext): void
    }
    class SeeTheFutureEffect {
        + apply(ctx: CardPlayContext): void
    }
    class ShuffleEffect {
        + apply(ctx: CardPlayContext): void
    }
    class NopeEffect {
        + apply(ctx: CardPlayContext): void
    }

    ExplodingKittenEffect ..|> CardEffect
    SeeTheFutureEffect ..|> CardEffect
    ShuffleEffect ..|> CardEffect
    NopeEffect ..|> CardEffect

    CardEffectRegistry --> ExplodingKittenEffect
    CardEffectRegistry --> SeeTheFutureEffect
    CardEffectRegistry --> ShuffleEffect
    CardEffectRegistry --> NopeEffect

    class Instantiator {
        + createCard(cardType: CardType): Card
        + createRandom(): Random
        + createCardList(): List<Card>
    }

    Instantiator --> Card
    Instantiator --> CardType

    enum GameType {
        NONE
        EXPLODING_KITTENS
        STREAKING_KITTENS
        IMPLODING_KITTENS
    }

    enum CardType {
        NOPE
        DEFUSE
        ATTACK
        SHUFFLE
        SKIP
        SEE_THE_FUTURE
        CAT_ONE
        CAT_TWO
        CAT_THREE
        CAT_FOUR
        EXPLODING_KITTEN
        STREAKING_KITTEN
        SWAP_TOP_AND_BOTTOM
        GARBAGE_COLLECTION
        CURSE_OF_THE_CAT_BUTT
        ALTER_THE_FUTURE
        CATOMIC_BOMB
        SUPER_SKIP
        MARK
        IMPLODING_KITTEN
        REVERSE
        FERAL_CAT
        TARGETED_ATTACK
        DRAW_FROM_THE_BOTTOM
    }
}

package view {

    class GameUI {
        - game: Game
        - messages: ResourceBundle
        - cardPlayService: CardPlayService

        + GameUI(game: Game)

        + chooseLanguage(): void
        + chooseGame(): void
        + chooseNumberOfPlayers(): void

        + startTurn(): void
        + endGame(): void
    }

    class Main {
        + main(args: String[]): void
    }
}

GameUI ..|> IGamePrompts
GameUI --> Game
GameUI --> Card
GameUI --> Player
GameUI --> CardPlayService


package controller {

    class GameController {
        - game: Game
        - ui: GameUI

        + GameController(game: Game, ui: GameUI)
        + runGame(): void
    }
}

GameController --> Game
GameController --> GameUI

Main --> GameController
Main --> GameUI
Main --> Game

@enduml
